name: islamicinstapp
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.0
  font_awesome_flutter: ^10.8.0
  phosphor_flutter: ^2.1.0
  lottie: ^3.3.1
  table_calendar: ^3.2.0
  provider: ^6.1.5
  get: ^4.7.2
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.6.11
  uuid: ^4.5.1
  flutter_launcher_icons: ^0.14.4
  shared_preferences: ^2.5.3
  image_picker: ^1.1.2
  firebase_storage: ^12.4.9
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/launchingicon.png"
  min_sdk_android: 21
