// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYHQrPhKprnleKBV10n-uYd3oj6gVHDvQ',
    appId: '1:1007558518465:web:01e1e01b501b9f520d9640',
    messagingSenderId: '1007558518465',
    projectId: 'ummahlink-39e9d',
    authDomain: 'ummahlink-39e9d.firebaseapp.com',
    storageBucket: 'ummahlink-39e9d.firebasestorage.app',
    measurementId: 'G-KYY7M50WST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDntf35YqMRywvoZDVpWNU120D62JCsbrE',
    appId: '1:1007558518465:android:2be0b59fccd122540d9640',
    messagingSenderId: '1007558518465',
    projectId: 'ummahlink-39e9d',
    storageBucket: 'ummahlink-39e9d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAox6wucuvaq6EW8EPNeVuS_vYqBBo9Ihk',
    appId: '1:1007558518465:ios:797c0f2fe2cb13400d9640',
    messagingSenderId: '1007558518465',
    projectId: 'ummahlink-39e9d',
    storageBucket: 'ummahlink-39e9d.firebasestorage.app',
    iosBundleId: 'com.example.islamicinstapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAox6wucuvaq6EW8EPNeVuS_vYqBBo9Ihk',
    appId: '1:1007558518465:ios:797c0f2fe2cb13400d9640',
    messagingSenderId: '1007558518465',
    projectId: 'ummahlink-39e9d',
    storageBucket: 'ummahlink-39e9d.firebasestorage.app',
    iosBundleId: 'com.example.islamicinstapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYHQrPhKprnleKBV10n-uYd3oj6gVHDvQ',
    appId: '1:1007558518465:web:1e2b12bfc3b6c7630d9640',
    messagingSenderId: '1007558518465',
    projectId: 'ummahlink-39e9d',
    authDomain: 'ummahlink-39e9d.firebaseapp.com',
    storageBucket: 'ummahlink-39e9d.firebasestorage.app',
    measurementId: 'G-7H6MTJ3284',
  );
}
